### ISSUE TITLE
Error translating -180, 90 in WGS84 to Web Mercator

### ISSUE THREAD

**Issue by dmfenton** [proj4js/proj4js#262]
Version: "2.4.4"

```
Trace: TypeError: Cannot read property 'x' of null
    at transformer (/Users/REDACTED/node_modules/proj4/dist/proj4-src.js:1868:32)
    at proj4$1 (/Users/REDACTED/node_modules/proj4/dist/proj4-src.js:1913:13)
```

coords
```
[-180, 90]
```

From
```json
"{
  "title": "WGS 84 (long/lat)",
  "projName": "longlat",
  "ellps": "WGS84",
  "datumCode": "WGS84",
  "units": "degrees",
  "datum_params": [
    "0",
    "0",
    "0"
  ],
  "datumName": "WGS84",
  "k0": 1,
  "axis": "enu",
  "names": [
    "longlat",
    "identity"
  ],
  "a": 6378137,
  "b": 6356752.314245179,
  "rf": 298.257223563,
  "es": 0.006694379990141316,
  "e": 0.08181919084262149,
  "ep2": 0.006739496742276434,
  "datum": {
    "datum_type": 4,
    "datum_params": [
      0,
      0,
      0
    ],
    "a": 6378137,
    "b": 6356752.314245179,
    "es": 0.006694379990141316,
    "ep2": 0.006739496742276434
  }
}"
```
to
```json
"{
  "title": "WGS 84 / Pseudo-Mercator",
  "projName": "merc",
  "a": 6378137,
  "b": 6378137,
  "lat_ts": 0,
  "long0": 0,
  "x0": 0,
  "y0": 0,
  "k0": 1,
  "units": "m",
  "datumCode": "none",
  "no_defs": true,
  "axis": "enu",
  "ellps": "wgs84",
  "names": [
    "Mercator",
    "Popular Visualisation Pseudo Mercator",
    "Mercator_1SP",
    "Mercator_Auxiliary_Sphere",
    "merc"
  ],
  "sphere": true,
  "es": 0,
  "e": 0,
  "ep2": 0,
  "datum": {
    "datum_type": 5,
    "a": 6378137,
    "b": 6378137,
    "es": 0,
    "ep2": 0
  }
}"
```

**Comment by dmfenton** [comment]
Looking into this a bit further, and this transformation is in fact invalid because web mercator does not contain these coordinates. I do think the error thrown could be more helpful

**Comment by jgravois** [comment]
yeah, 90deg is infinity in web mercator
