### ISSUE TITLE
Build error on vercel using vite

### ISSUE THREAD

**Issue by ZulluBalti** [proj4js/proj4js#435]
Hi, I'm using vite with React, OpenLayer and proj4 and it's all working file in development but when I push the code I got this error.

```
[13:23:32.975] Running build in Washington, D.C., USA (East) – iad1
[13:23:33.027] Cloning github.com/janheinvanasseldonk/ai (Branch: main, Commit: 5418ee2)
[13:23:33.495] Cloning completed: 467.795ms
[13:23:34.446] Restored build cache
[13:23:34.472] Running "vercel build"
[13:23:34.882] Vercel CLI 29.1.1
[13:23:35.450] Installing dependencies...
[13:23:35.705] yarn install v1.22.17
[13:23:35.735] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[13:23:35.738] [1/4] Resolving packages...
[13:23:35.804] success Already up-to-date.
[13:23:35.806] Done in 0.10s.
[13:23:35.839] Running "yarn run build"
[13:23:36.004] yarn run v1.22.17
[13:23:36.022] $ vite build
[13:23:36.393] [36mvite v4.1.4 [32mbuilding for production...[36m[39m
[13:23:36.419] transforming...
[13:23:37.956] [32m✓[39m 347 modules transformed.
[13:23:37.957] [31mCould not resolve "./window" from "node_modules/proj4/lib/defs.js"[39m
[13:23:37.957] file: [36m/vercel/path0/node_modules/proj4/lib/defs.js[39m
[13:23:37.958] [31merror during build:
[13:23:37.958] RollupError: Could not resolve "./window" from "node_modules/proj4/lib/defs.js"
[13:23:37.958]     at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
[13:23:37.958]     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23777:24)
[13:23:37.959]     at file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23739:26[39m
[13:23:37.980] error Command failed with exit code 1.
[13:23:37.980] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:23:38.003] Error: Command "yarn run build" exited with 1
[13:23:38.680] Deployment completed
[13:23:38.252] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**Comment by ahocevar** [comment]
This looks like a bug somewhere in the build tools vercel is using. I don't know exactly what the problem is, but an educated guess from looking at the log output above is that rollup tries to transform `import globals from './global';` into `import globals from './window';`.

**Comment by ZulluBalti** [comment]
I run ```yarn run build``` locally and got the same error

```
yarn run v1.22.19 
$ vite build 
vite v4.1.4 building for production... 
✓ 309 modules transformed. 
Could not resolve "./window" from "node_modules/proj4/lib/defs.js" 
file: /home/zullu/Documents/drone-frontend/node_modules/proj4/lib/defs.js 
error during build: 
RollupError: Could not resolve "./window" from "node_modules/proj4/lib/defs.js" 
    at error (file:///home/zullu/Documents/drone-frontend/node_modules/rollup/dist/es/shared/node-entry.js:2125:30) 
    at ModuleLoader.handleInvalidResolvedId (file:///home/zullu/Documents/drone-frontend/node_modules/rollup/dist/es/shared/node-entry.js:23777:24) 
    at file:///home/zullu/Documents/drone-frontend/node_modules/rollup/dist/es/shared/node-entry.js:23739:26 
error Command failed with exit code 1. 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

**Comment by ahocevar** [comment]
Probably. You can try to rename `./lib/global.js` to something different, and change the imports accordingly. If that fixes the problem, then it is an issue with vite or rollup.

**Comment by ZulluBalti** [comment]
> Probably. You can try to rename `./lib/global.js` to something different, and change the imports accordingly. If that fixes the problem, then it is an issue with vite or rollup.

renaming global.js to window.js solves the issue, but how can I do that in production (vercel) as it automatically download these packages and run the build script? But i guess that an issue with vite not proj4

**Comment by ahocevar** [comment]
Yes, you'd have to report the issue to vite.
